# Generated by Django 3.2 on 2022-03-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
