version: '3.3'
services:
    redis:
        image: redis
        command: redis-server
        ports:
            - "14000:6379"
    db:
        image: postgres
        environment:
            - POSTGRES_USER=training
            - POSTGRES_PASSWORD=training
            - POSTGRES_DB=training
        ports:
            - "127.0.0.1:8000:5432"
    web:
        build: .
        restart: always
        command: python manage.py runserver 0.0.0.0:8000
        env_file:
            - ./api/config/settings/.env
        ports:
            - "127.0.0.1:8600:8000"
        volumes:
            - .:/code
        links:
            - db
            - redis
        depends_on:
            - db
            - redis
