# Generated by Django 3.2 on 2022-03-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20220316_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Is shopping', 'Is shopping'), ('Cancelled', 'Cancelled'), ('Done', 'Done'), ('Refunded', 'Refunded')], max_length=20, null=True),
        ),
    ]
