# Generated by Django 3.2 on 2022-03-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_csvlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvlog',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
