# Generated by Django 3.2 on 2022-03-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['code'], name='product_pro_code_f66008_idx'),
        ),
    ]
