# Generated by Django 3.2 on 2022-03-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20220311_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['title'], name='product_cat_title_74c9a5_idx'),
        ),
    ]
